"""Create table UserCategory

Revision ID: 1da781124cbd
Revises: 46bfc326b354
Create Date: 2023-02-12 11:29:32.316190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da781124cbd'
down_revision = '46bfc326b354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_category', ['user_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type')
    op.drop_table('user_category')
    # ### end Alembic commands ###
