"""Rename table to UserSubject, create tables: ReaderDevice, ControlDevice

Revision ID: 4739f39090eb
Revises: 881bef7634a2
Create Date: 2023-02-12 11:57:43.750572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4739f39090eb'
down_revision = '881bef7634a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['user_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reader_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['user_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_object')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_object',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_object_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_object_pkey')
    )
    op.drop_table('reader_device')
    op.drop_table('control_device')
    op.drop_table('user_subject')
    # ### end Alembic commands ###
