"""Create table UserObject

Revision ID: 881bef7634a2
Revises: 1da781124cbd
Create Date: 2023-02-12 11:42:03.255318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881bef7634a2'
down_revision = '1da781124cbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_object')
    # ### end Alembic commands ###
