"""Initial

Revision ID: b53462dfff05
Revises: 
Create Date: 2023-04-11 11:03:47.638192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53462dfff05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type'], ['user_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['user_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reader_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['user_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['control_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('read_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['reader_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_sensor')
    op.drop_table('control_sensor')
    op.drop_table('reader_device')
    op.drop_table('control_device')
    op.drop_table('user_subject')
    op.drop_table('user')
    op.drop_table('user_category')
    # ### end Alembic commands ###
